name: CI Checks
on: [pull_request]

jobs:
  install-tools:
    name: Install tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Install tools
        run: ./scripts/install-tools.sh
      - name: Cache tools
        uses: actions/cache@v4.2.4
        with:
          path: ~/.rokit
          key: tools-${{ hashFiles('rokit.toml') }}

  lint:
    name: Lint with Selene
    runs-on: ubuntu-latest
    needs: [install-tools]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Restore cached tools
        uses: actions/cache@v4.2.4
        with:
          path: ~/.rokit
          key: tools-${{ hashFiles('rokit.toml') }}
      - name: Lint
        run: ./scripts/lint.sh

  style:
    name: Format with Stylua
    runs-on: ubuntu-latest
    needs: [install-tools]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Restore cached tools
        uses: actions/cache@v4.2.4
        with:
          path: ~/.rokit
          key: tools-${{ hashFiles('rokit.toml') }}
      - name: Style
        run: ./scripts/style.sh
